repository 'cloudera', 'https://repository.cloudera.com/artifactory/cloudera-repos/'

jar 'org.apache.hadoop:hadoop-common', '2.6.0-cdh5.11.0'
jar 'org.apache.hadoop:hadoop-hdfs',   '2.6.0-cdh5.11.0'
jar 'org.apache.kudu:kudu-client',     '1.3.1'
